./mvnw spring-boot-:run -Dspring-boot.run.arguments=--datadumb.location.works=/D:/java-brains-code-with-me/properties-file/xaa &
./mvnw spring-boot-:run -Dspring-boot.run.arguments=--datadumb.location.works=/D:/java-brains-code-with-me/properties-file/xab &
./mvnw spring-boot-:run -Dspring-boot.run.arguments=--datadumb.location.works=/D:/java-brains-code-with-me/properties-file/xac &
./mvnw spring-boot-:run -Dspring-boot.run.arguments=--datadumb.location.works=/D:/java-brains-code-with-me/properties-file/xad &
./mvnw spring-boot-:run -Dspring-boot.run.arguments=--datadumb.location.works=/D:/java-brains-code-with-me/properties-file/xae &
./mvnw spring-boot-:run -Dspring-boot.run.arguments=--datadumb.location.works=/D:/java-brains-code-with-me/properties-file/xaf &
./mvnw spring-boot-:run -Dspring-boot.run.arguments=--datadumb.location.works=/D:/java-brains-code-with-me/properties-file/xag &
./mvnw spring-boot-:run -Dspring-boot.run.arguments=--datadumb.location.works=/D:/java-brains-code-with-me/properties-file/xah &
./mvnw spring-boot-:run -Dspring-boot.run.arguments=--datadumb.location.works=/D:/java-brains-code-with-me/properties-file/xai &
./mvnw spring-boot-:run -Dspring-boot.run.arguments=--datadumb.location.works=/D:/java-brains-code-with-me/properties-file/xaj &
./mvnw spring-boot-:run -Dspring-boot.run.arguments=--datadumb.location.works=/D:/java-brains-code-with-me/properties-file/xak &